require('config.colorscheme')
-- require('config.completion')
require('config.fugitive')
require('config.lspkind')
require('config.telescope')
require('config.galaxyline')
require('config.gitsign')
require('config.bufferline')
require('config.treesetter')
require('config.easymotion')
require('config.nvim-compe')
require('config.fluttertools')
