require("nvim-highlight-colors").setup {
  ---Render style
  ---@usage 'background'|'foreground'|'virtual'
  render = 'virtual',

  ---Set virtual symbol (requires render to be set to 'virtual')
  virtual_symbol = '██',

  ---Set virtual symbol suffix (defaults to '')
  virtual_symbol_prefix = '',

  ---Set virtual symbol suffix (defaults to ' ')
  virtual_symbol_suffix = '',

  ---Set virtual symbol position()
  ---@usage 'inline'|'eol'|'eow'
  ---inline mimics VS Code style
  ---eol stands for `end of column` - Recommended to set `virtual_symbol_suffix = ''` when used.
  ---eow stands for `end of word` - Recommended to set `virtual_symbol_prefix = ' ' and virtual_symbol_suffix = ''` when used.
  virtual_symbol_position = 'eol',

  ---Highlight hex colors, e.g. '#FFFF'
  enable_hex = true,

  ---Highlight short hex colors e.g. '#fff'
  enable_short_hex = true,

  ---Highlight rgb colors, e.g. 'rgb(0 0 0)'
  enable_rgb = true,

  ---Highlight hsl colors, e.g. 'hsl(150deg 30% 40%)'
  enable_hsl = true,

  ---Highlight CSS variables, e.g. 'var(--testing-color)'
  enable_var_usage = true,

  ---Highlight named colors, e.g. 'green'
  enable_named_colors = true,

  ---Highlight tailwind colors, e.g. 'bg-blue-500'
  enable_tailwind = false,

  ---Set custom colors
  ---Label must be properly escaped with '%' to adhere to `string.gmatch`
  --- :help string.gmatch
  custom_colors = {
    { label = '%-%-theme%-primary%-color',   color = '#0f1219' },
    { label = "WHITE10",                color = "#1AFFFF" },
    { label = "WHITE12",                color = "#1FFFFF" },
    { label = "WHITE24",                color = "#3DFFFF" },
    { label = "WHITE30",                color = "#4DFFFF" },
    { label = "WHITE38",                color = "#62FFFF" },
    { label = "WHITE54",                color = "#8AFFFF" },
    { label = "WHITE60",                color = "#99FFFF" },
    { label = "WHITE70",                color = "#B3FFFF" },
    { label = "WHITE",                  color = "#FFFFFF" },
    { label = "TRANSPARENT",            color = "#000000" },
    { label = "BLACK12",                color = "#1F0000" },
    { label = "BLACK26",                color = "#420000" },
    { label = "BLACK38",                color = "#610000" },
    { label = "BLACK45",                color = "#730000" },
    { label = "BLACK54",                color = "#8A0000" },
    { label = "BLACK87",                color = "#DD0000" },
    { label = "BLACK",                       color = "#000000" },
    { label = "RED",                         color = "#F44336" },
    { label = "RED_50",                      color = "#FFEBEE" },
    { label = "RED_100",                     color = "#FFCDD2" },
    { label = "RED_200",                     color = "#EF9A9A" },
    { label = "RED_300",                     color = "#E57373" },
    { label = "RED_400",                     color = "#EF5350" },
    { label = "RED_500",                     color = "#F44336" },
    { label = "RED_600",                     color = "#E53935" },
    { label = "RED_700",                     color = "#D32F2F" },
    { label = "RED_800",                     color = "#C62828" },
    { label = "RED_900",                     color = "#B71C1C" },
    { label = "PINK",                        color = "#E91E63" },
    { label = "PINK_50",                     color = "#FCE4EC" },
    { label = "PINK_100",                    color = "#F8BBD0" },
    { label = "PINK_200",                    color = "#F48FB1" },
    { label = "PINK_300",                    color = "#F06292" },
    { label = "PINK_400",                    color = "#EC407A" },
    { label = "PINK_500",                    color = "#E91E63" },
    { label = "PINK_600",                    color = "#D81B60" },
    { label = "PINK_700",                    color = "#C2185B" },
    { label = "PINK_800",                    color = "#AD1457" },
    { label = "PINK_900",                    color = "#880E4F" },
    { label = "PURPLE",                      color = "#9C27B0" },
    { label = "PURPLE_50",                   color = "#F3E5F5" },
    { label = "PURPLE_100",                  color = "#E1BEE7" },
    { label = "PURPLE_200",                  color = "#CE93D8" },
    { label = "PURPLE_300",                  color = "#BA68C8" },
    { label = "PURPLE_400",                  color = "#AB47BC" },
    { label = "PURPLE_500",                  color = "#9C27B0" },
    { label = "PURPLE_600",                  color = "#8E24AA" },
    { label = "PURPLE_700",                  color = "#7B1FA2" },
    { label = "PURPLE_800",                  color = "#6A1B9A" },
    { label = "PURPLE_900",                  color = "#4A148C" },
    { label = "DEEP_PURPLE",                 color = "#673AB7" },
    { label = "DEEP_PURPLE_50",              color = "#EDE7F6" },
    { label = "DEEP_PURPLE_100",             color = "#D1C4E9" },
    { label = "DEEP_PURPLE_200",             color = "#B39DDB" },
    { label = "DEEP_PURPLE_300",             color = "#9575CD" },
    { label = "DEEP_PURPLE_400",             color = "#7E57C2" },
    { label = "DEEP_PURPLE_500",             color = "#673AB7" },
    { label = "DEEP_PURPLE_600",             color = "#5E35B1" },
    { label = "DEEP_PURPLE_700",             color = "#512DA8" },
    { label = "DEEP_PURPLE_800",             color = "#4527A0" },
    { label = "DEEP_PURPLE_900",             color = "#311B92" },
    { label = "INDIGO",                      color = "#3F51B5" },
    { label = "INDIGO_50",                   color = "#E8EAF6" },
    { label = "INDIGO_100",                  color = "#C5CAE9" },
    { label = "INDIGO_200",                  color = "#9FA8DA" },
    { label = "INDIGO_300",                  color = "#7986CB" },
    { label = "INDIGO_400",                  color = "#5C6BC0" },
    { label = "INDIGO_500",                  color = "#3F51B5" },
    { label = "INDIGO_600",                  color = "#3949AB" },
    { label = "INDIGO_700",                  color = "#303F9F" },
    { label = "INDIGO_800",                  color = "#283593" },
    { label = "INDIGO_900",                  color = "#1A237E" },
    { label = "BLUE",                        color = "#2196F3" },
    { label = "BLUE_50",                     color = "#E3F2FD" },
    { label = "BLUE_100",                    color = "#BBDEFB" },
    { label = "BLUE_200",                    color = "#90CAF9" },
    { label = "BLUE_300",                    color = "#64B5F6" },
    { label = "BLUE_400",                    color = "#42A5F5" },
    { label = "BLUE_500",                    color = "#2196F3" },
    { label = "BLUE_600",                    color = "#1E88E5" },
    { label = "BLUE_700",                    color = "#1976D2" },
    { label = "BLUE_800",                    color = "#1565C0" },
    { label = "BLUE_900",                    color = "#0D47A1" },
    { label = "LIGHT_BLUE",                  color = "#03A9F4" },
    { label = "LIGHT_BLUE_50",               color = "#E1F5FE" },
    { label = "LIGHT_BLUE_100",              color = "#B3E5FC" },
    { label = "LIGHT_BLUE_200",              color = "#81D4FA" },
    { label = "LIGHT_BLUE_300",              color = "#4FC3F7" },
    { label = "LIGHT_BLUE_400",              color = "#29B6F6" },
    { label = "LIGHT_BLUE_500",              color = "#03A9F4" },
    { label = "LIGHT_BLUE_600",              color = "#039BE5" },
    { label = "LIGHT_BLUE_700",              color = "#0288D1" },
    { label = "LIGHT_BLUE_800",              color = "#0277BD" },
    { label = "LIGHT_BLUE_900",              color = "#01579B" },
    { label = "CYAN",                        color = "#00BCD4" },
    { label = "CYAN_50",                     color = "#E0F7FA" },
    { label = "CYAN_100",                    color = "#B2EBF2" },
    { label = "CYAN_200",                    color = "#80DEEA" },
    { label = "CYAN_300",                    color = "#4DD0E1" },
    { label = "CYAN_400",                    color = "#26C6DA" },
    { label = "CYAN_500",                    color = "#00BCD4" },
    { label = "CYAN_600",                    color = "#00ACC1" },
    { label = "CYAN_700",                    color = "#0097A7" },
    { label = "CYAN_800",                    color = "#00838F" },
    { label = "CYAN_900",                    color = "#006064" },
    { label = "TEAL",                        color = "#009688" },
    { label = "TEAL_50",                     color = "#E0F2F1" },
    { label = "TEAL_100",                    color = "#B2DFDB" },
    { label = "TEAL_200",                    color = "#80CBC4" },
    { label = "TEAL_300",                    color = "#4DB6AC" },
    { label = "TEAL_400",                    color = "#26A69A" },
    { label = "TEAL_500",                    color = "#009688" },
    { label = "TEAL_600",                    color = "#00897B" },
    { label = "TEAL_700",                    color = "#00796B" },
    { label = "TEAL_800",                    color = "#00695C" },
    { label = "TEAL_900",                    color = "#004D40" },
    { label = "GREEN",                       color = "#4CAF50" },
    { label = "GREEN_50",                    color = "#E8F5E9" },
    { label = "GREEN_100",                   color = "#C8E6C9" },
    { label = "GREEN_200",                   color = "#A5D6A7" },
    { label = "GREEN_300",                   color = "#81C784" },
    { label = "GREEN_400",                   color = "#66BB6A" },
    { label = "GREEN_500",                   color = "#4CAF50" },
    { label = "GREEN_600",                   color = "#43A047" },
    { label = "GREEN_700",                   color = "#388E3C" },
    { label = "GREEN_800",                   color = "#2E7D32" },
    { label = "GREEN_900",                   color = "#1B5E20" },
    { label = "LIGHT_GREEN",                 color = "#8BC34A" },
    { label = "LIGHT_GREEN_50",              color = "#F1F8E9" },
    { label = "LIGHT_GREEN_100",             color = "#DCEDC8" },
    { label = "LIGHT_GREEN_200",             color = "#C5E1A5" },
    { label = "LIGHT_GREEN_300",             color = "#AED581" },
    { label = "LIGHT_GREEN_400",             color = "#9CCC65" },
    { label = "LIGHT_GREEN_500",             color = "#8BC34A" },
    { label = "LIGHT_GREEN_600",             color = "#7CB342" },
    { label = "LIGHT_GREEN_700",             color = "#689F38" },
    { label = "LIGHT_GREEN_800",             color = "#558B2F" },
    { label = "LIGHT_GREEN_900",             color = "#33691E" },
    { label = "LIME",                        color = "#CDDC39" },
    { label = "LIME_50",                     color = "#F9FBE7" },
    { label = "LIME_100",                    color = "#F0F4C3" },
    { label = "LIME_200",                    color = "#E6EE9C" },
    { label = "LIME_300",                    color = "#DCE775" },
    { label = "LIME_400",                    color = "#D4E157" },
    { label = "LIME_500",                    color = "#CDDC39" },
    { label = "LIME_600",                    color = "#C0CA33" },
    { label = "LIME_700",                    color = "#AFB42B" },
    { label = "LIME_800",                    color = "#9E9D24" },
    { label = "LIME_900",                    color = "#827717" },
    { label = "YELLOW",                      color = "#FFEB3B" },
    { label = "YELLOW_50",                   color = "#FFFDE7" },
    { label = "YELLOW_100",                  color = "#FFF9C4" },
    { label = "YELLOW_200",                  color = "#FFF59D" },
    { label = "YELLOW_300",                  color = "#FFF176" },
    { label = "YELLOW_400",                  color = "#FFEE58" },
    { label = "YELLOW_500",                  color = "#FFEB3B" },
    { label = "YELLOW_600",                  color = "#FDD835" },
    { label = "YELLOW_700",                  color = "#FBC02D" },
    { label = "YELLOW_800",                  color = "#F9A825" },
    { label = "YELLOW_900",                  color = "#F57F17" },
    { label = "AMBER",                       color = "#FFC107" },
    { label = "AMBER_50",                    color = "#FFF8E1" },
    { label = "AMBER_100",                   color = "#FFECB3" },
    { label = "AMBER_200",                   color = "#FFE082" },
    { label = "AMBER_300",                   color = "#FFD54F" },
    { label = "AMBER_400",                   color = "#FFCA28" },
    { label = "AMBER_500",                   color = "#FFC107" },
    { label = "AMBER_600",                   color = "#FFB300" },
    { label = "AMBER_700",                   color = "#FFA000" },
    { label = "AMBER_800",                   color = "#FF8F00" },
    { label = "AMBER_900",                   color = "#FF6F00" },
    { label = "ORANGE",                      color = "#FF9800" },
    { label = "ORANGE_50",                   color = "#FFF3E0" },
    { label = "ORANGE_100",                  color = "#FFE0B2" },
    { label = "ORANGE_200",                  color = "#FFCC80" },
    { label = "ORANGE_300",                  color = "#FFB74D" },
    { label = "ORANGE_400",                  color = "#FFA726" },
    { label = "ORANGE_500",                  color = "#FF9800" },
    { label = "ORANGE_600",                  color = "#FB8C00" },
    { label = "ORANGE_700",                  color = "#F57C00" },
    { label = "ORANGE_800",                  color = "#EF6C00" },
    { label = "ORANGE_900",                  color = "#E65100" },
    { label = "DEEP_ORANGE",                 color = "#FF5722" },
    { label = "DEEP_ORANGE_50",              color = "#FBE9E7" },
    { label = "DEEP_ORANGE_100",             color = "#FFCCBC" },
    { label = "DEEP_ORANGE_200",             color = "#FFAB91" },
    { label = "DEEP_ORANGE_300",             color = "#FF8A65" },
    { label = "DEEP_ORANGE_400",             color = "#FF7043" },
    { label = "DEEP_ORANGE_500",             color = "#FF5722" },
    { label = "DEEP_ORANGE_600",             color = "#F4511E" },
    { label = "DEEP_ORANGE_700",             color = "#E64A19" },
    { label = "DEEP_ORANGE_800",             color = "#D84315" },
    { label = "DEEP_ORANGE_900",             color = "#BF360C" },
    { label = "BROWN",                       color = "#795548" },
    { label = "BROWN_50",                    color = "#EFEBE9" },
    { label = "BROWN_100",                   color = "#D7CCC8" },
    { label = "BROWN_200",                   color = "#BCAAA4" },
    { label = "BROWN_300",                   color = "#A1887F" },
    { label = "BROWN_400",                   color = "#8D6E63" },
    { label = "BROWN_500",                   color = "#795548" },
    { label = "BROWN_600",                   color = "#6D4C41" },
    { label = "BROWN_700",                   color = "#5D4037" },
    { label = "BROWN_800",                   color = "#4E342E" },
    { label = "BROWN_900",                   color = "#3E2723" },
    { label = "BLUE_GREY",                   color = "#607D8B" },
    { label = "BLUE_GREY_50",                color = "#ECEFF1" },
    { label = "BLUE_GREY_100",               color = "#CFD8DC" },
    { label = "BLUE_GREY_200",               color = "#B0BEC5" },
    { label = "BLUE_GREY_300",               color = "#90A4AE" },
    { label = "BLUE_GREY_400",               color = "#78909C" },
    { label = "BLUE_GREY_500",               color = "#607D8B" },
    { label = "BLUE_GREY_600",               color = "#546E7A" },
    { label = "BLUE_GREY_700",               color = "#455A64" },
    { label = "BLUE_GREY_800",               color = "#37474F" },
    { label = "BLUE_GREY_900",               color = "#263238" },
    { label = "RED_ACCENT",                  color = "#FF5252" },
    { label = "RED_ACCENT_100",              color = "#FF8A80" },
    { label = "RED_ACCENT_200",              color = "#FF5252" },
    { label = "RED_ACCENT_400",              color = "#FF1744" },
    { label = "RED_ACCENT_700",              color = "#D50000" },
    { label = "PINK_ACCENT",                 color = "#FF4081" },
    { label = "PINK_ACCENT_100",             color = "#FF80AB" },
    { label = "PINK_ACCENT_200",             color = "#FF4081" },
    { label = "PINK_ACCENT_400",             color = "#F50057" },
    { label = "PINK_ACCENT_700",             color = "#C51162" },
    { label = "PURPLE_ACCENT",               color = "#E040FB" },
    { label = "PURPLE_ACCENT_100",           color = "#EA80FC" },
    { label = "PURPLE_ACCENT_200",           color = "#E040FB" },
    { label = "PURPLE_ACCENT_400",           color = "#D500F9" },
    { label = "PURPLE_ACCENT_700",           color = "#AA00FF" },
    { label = "DEEP_PURPLE_ACCENT",          color = "#7C4DFF" },
    { label = "DEEP_PURPLE_ACCENT_100",      color = "#B388FF" },
    { label = "DEEP_PURPLE_ACCENT_200",      color = "#7C4DFF" },
    { label = "DEEP_PURPLE_ACCENT_400",      color = "#651FFF" },
    { label = "DEEP_PURPLE_ACCENT_700",      color = "#6200EA" },
    { label = "INDIGO_ACCENT",               color = "#536DFE" },
    { label = "INDIGO_ACCENT_100",           color = "#8C9EFF" },
    { label = "INDIGO_ACCENT_200",           color = "#536DFE" },
    { label = "INDIGO_ACCENT_400",           color = "#3D5AFE" },
    { label = "INDIGO_ACCENT_700",           color = "#304FFE" },
    { label = "BLUE_ACCENT",                 color = "#448AFF" },
    { label = "BLUE_ACCENT_100",             color = "#82B1FF" },
    { label = "BLUE_ACCENT_200",             color = "#448AFF" },
    { label = "BLUE_ACCENT_400",             color = "#2979FF" },
    { label = "BLUE_ACCENT_700",             color = "#2962FF" },
    { label = "LIGHT_BLUE_ACCENT",           color = "#40C4FF" },
    { label = "LIGHT_BLUE_ACCENT_100",       color = "#80D8FF" },
    { label = "LIGHT_BLUE_ACCENT_200",       color = "#40C4FF" },
    { label = "LIGHT_BLUE_ACCENT_400",       color = "#00B0FF" },
    { label = "LIGHT_BLUE_ACCENT_700",       color = "#0091EA" },
    { label = "CYAN_ACCENT",                 color = "#18FFFF" },
    { label = "CYAN_ACCENT_100",             color = "#84FFFF" },
    { label = "CYAN_ACCENT_200",             color = "#18FFFF" },
    { label = "CYAN_ACCENT_400",             color = "#00E5FF" },
    { label = "CYAN_ACCENT_700",             color = "#00B8D4" },
    { label = "TEAL_ACCENT",                 color = "#64FFDA" },
    { label = "TEAL_ACCENT_100",             color = "#A7FFEB" },
    { label = "TEAL_ACCENT_200",             color = "#64FFDA" },
    { label = "TEAL_ACCENT_400",             color = "#1DE9B6" },
    { label = "TEAL_ACCENT_700",             color = "#00BFA5" },
    { label = "GREEN_ACCENT",                color = "#69F0AE" },
    { label = "GREEN_ACCENT_100",            color = "#B9F6CA" },
    { label = "GREEN_ACCENT_200",            color = "#69F0AE" },
    { label = "GREEN_ACCENT_400",            color = "#00E676" },
    { label = "GREEN_ACCENT_700",            color = "#00C853" },
    { label = "LIGHT_GREEN_ACCENT",          color = "#B2FF59" },
    { label = "LIGHT_GREEN_ACCENT_100",      color = "#CCFF90" },
    { label = "LIGHT_GREEN_ACCENT_200",      color = "#B2FF59" },
    { label = "LIGHT_GREEN_ACCENT_400",      color = "#76FF03" },
    { label = "LIGHT_GREEN_ACCENT_700",      color = "#64DD17" },
    { label = "LIME_ACCENT",                 color = "#EEFF41" },
    { label = "LIME_ACCENT_100",             color = "#F4FF81" },
    { label = "LIME_ACCENT_200",             color = "#EEFF41" },
    { label = "LIME_ACCENT_400",             color = "#C6FF00" },
    { label = "LIME_ACCENT_700",             color = "#AEEA00" },
    { label = "YELLOW_ACCENT",               color = "#FFFF00" },
    { label = "YELLOW_ACCENT_100",           color = "#FFFF8D" },
    { label = "YELLOW_ACCENT_200",           color = "#FFFF00" },
    { label = "YELLOW_ACCENT_400",           color = "#FFEA00" },
    { label = "YELLOW_ACCENT_700",           color = "#FFD600" },
    { label = "AMBER_ACCENT",                color = "#FFD740" },
    { label = "AMBER_ACCENT_100",            color = "#FFE57F" },
    { label = "AMBER_ACCENT_200",            color = "#FFD740" },
    { label = "AMBER_ACCENT_400",            color = "#FFC400" },
    { label = "AMBER_ACCENT_700",            color = "#FFAB00" },
    { label = "ORANGE_ACCENT",               color = "#FFAB40" },
    { label = "ORANGE_ACCENT_100",           color = "#FFD180" },
    { label = "ORANGE_ACCENT_200",           color = "#FFAB40" },
    { label = "ORANGE_ACCENT_400",           color = "#FF9100" },
    { label = "ORANGE_ACCENT_700",           color = "#FF6D00" },
    { label = "DEEP_ORANGE_ACCENT",          color = "#FF6E40" },
    { label = "DEEP_ORANGE_ACCENT_100",      color = "#FF9E80" },
    { label = "DEEP_ORANGE_ACCENT_200",      color = "#FF6E40" },
    { label = "DEEP_ORANGE_ACCENT_400",      color = "#FF3D00" },
    { label = "DEEP_ORANGE_ACCENT_700",      color = "#DD2C00" },
    { label = "GREY",                        color = "#9E9E9E" },
    { label = "GREY_50",                     color = "#FAFAFA" },
    { label = "GREY_100",                    color = "#F5F5F5" },
    { label = "GREY_200",                    color = "#EEEEEE" },
    { label = "GREY_300",                    color = "#E0E0E0" },
    { label = "GREY_400",                    color = "#BDBDBD" },
    { label = "GREY_500",                    color = "#9E9E9E" },
    { label = "GREY_600",                    color = "#757575" },
    { label = "GREY_700",                    color = "#616161" },
    { label = "GREY_800",                    color = "#424242" },
    { label = "GREY_900",                    color = "#212121" },
    { label = '%-%-theme%-secondary%-color', color = '#5a5d64' },
  },

  -- Exclude filetypes or buftypes from highlighting e.g. 'exclude_buftypes = {'text'}'
  exclude_filetypes = {"md", "norg", "markdown"},
  exclude_buftypes = {}
}
